apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka_exporter.fullname" . }}
  labels:
    {{- include "kafka_exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kafka_exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "kafka_exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kafka_exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- if .Values.kafkaExporter.address }}
            - "--address={{ .Values.kafkaExporter.address }}"
            {{- end }}
            {{- if .Values.kafkaExporter.address }}
            - "--broker={{ .Values.kafkaExporter.broker }}"
            {{- end }}
            {{- if .Values.kafkaExporter.saslUsername }}
            - "--sasl.username={{ .Values.kafkaExporter.saslUsername }}"
            {{- end }}
            {{- if .Values.kafkaExporter.saslPassword }}
            - "--sasl.password={{ .Values.kafkaExporter.saslPassword }}"
            {{- end }}
            {{- if .Values.kafkaExporter.mechanisms }}
            - "--sasl.mechanisms={{ .Values.kafkaExporter.mechanisms }}"
            {{- end }}
            {{- if .Values.kafkaExporter.tls }}
            - "--tls"
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
