apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka_exporter.fullname" . }}-{{ .Release.Revision }}
  labels:
  {{- include "kafka_exporter.labels" . | nindent 4 }}
type: Opaque
data:
  saslUsername: {{ .Values.kafkaExporter.saslUsername | b64enc | quote }}
  saslPassword: {{ .Values.kafkaExporter.saslPassword | b64enc | quote }}
